<?
include("header.phtml");
?>
    <!-- End -->
    <body>
    <aside class="aside">

    </aside>
    <div class="catalog_lines" style="padding-bottom: 1rem;">
        <div class="catalog_new container-fluid">
            <div class="products container-fluid">
                <!--   <div class="row row-cols-1">
                       <div class="col">
                           <div class="head_row"><a style="font-size: 20px"><b>Новинки</b></a></div>
                       </div>
                   </div> -->

                <div class="row_info">
                    <a style="font-size: 22px"><b>Лучшие из лучших</b></a>
                </div>
                <div class="row"> <!-- row-cols-5 -->
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/бегущий.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#" style="text-decoration:none">Бегущий в лабиринте</a>
                                <a style="color: #A4A4A4; font-size: 0.6rem">Дэшнер Джеймс</a>
                            </p>
                            <div class="credit">
                                <a style="font-size: 20px"><b>559p.</b></a>
                                <button class="buy_button">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="catalog_product">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/мараиморок.jpeg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none">Мара и морок</a>
                                <a style="color: #A4A4A4; font-size: 0.6rem">Арден Ли</a>
                            </p>
                            <div class="credit">
                                <a style="font-size: 20px"><b>699p.</b></a>
                                <button class="buy_button">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="catalog_product">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/властелин%20колец.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none">Властелин колец</a>
                                <a style="color: #A4A4A4; font-size: 0.6rem">Руэл Толкин</a>
                            </p>
                            <div class="credit">
                                <a style="font-size: 20px"><b>559p.</b></a>
                                <button class="buy_button">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="catalog_product">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/гарри%20поттер.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none">Гарри Поттер. Книга 1-ая</a>
                                <a style="color: #A4A4A4; font-size: 0.6rem">Роан Джоулинг</a>
                            </p>
                            <div class="credit">
                                <a style="font-size: 20px"><b>729p.</b></a>
                                <button class="buy_button">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="catalog_product">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/саксонец.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none">Саксонец. Меч Роланда</a>
                                <a style="color: #A4A4A4; font-size: 0.6rem">Тим Севери</a>
                            </p>
                            <div class="credit">
                                <a style="font-size: 20px"><b>499p.</b></a>
                                <button class="buy_button">Купить</button>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
    </body>

<?
include("footer.phtml");
?>