<?
include("header.phtml");
?>
<!-- End -->

<div id="menu">
    <div id="carouselProductControls" class="carousel slide product__carousel" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active product__carousel-item item1">
                <img src="img/bootstrap_pic1.jpg" class="d-block w-100 product__carousel_img_1"
                     alt="carousel_image">
                <div class="carousel_content">
                    <div class="text_info">
                        <div class="info_title">Загляни в себя</div>
                        <div class="info_text">Скидки до <b>30%</b> на подборки книг о самооценке, личной эффективности и не только</div>
                    </div>
                    <button class="carousel-button">Купить</button>
                </div>

            </div>
            <div class="carousel-item product__carousel-item">
                <img src="img/bootstrap_pic22.jpg" class="d-block w-100 product__carousel_img_2"
                     alt="carousel_image">
                <div class="carousel_content2" style="padding: 2rem;">
                    <div class="text_info">
                        <div class="info_title" style="color: #222224;">Что почитать?</div>
                        <div class="info_text" style="color: #222224;">Наша редакция специально собрала коллекцию — в ней собрана литература с самыми хорошими отзывами!</div>
                    </div>
                    <button class="carousel-button" style="margin-top: 1rem;">Перейти</button>
                </div>
            </div>
            <div class="carousel-item product__carousel-item">
                <img src="img/bootstrap_pic3.jpg" class="d-block w-100 product__carousel_img_3"
                     alt="carousel_image">
                <div class="carousel_content2">
                    <div class="text_info">
                        <div class="info_title"  style="color: #222224;">Ведьмина служба доставки</div>
                        <div class="info_text"  style="color: #222224;">Спешите узнать уникальную историю девочки, работающей по ведьминской профессии</div>
                    </div>
                    <button class="carousel-button">Перейти</button>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselProductControls"
                data-bs-slide="prev">
            <i class="fas fa-angle-left product__icon"></i>
            <span class="carousel-control-prev-icon product__carousel_icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselProductControls"
                data-bs-slide="next">
            <i class="fas fa-angle-right product__icon"></i>
            <span class="carousel-control-next-icon product__carousel_icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <div class="column_lines" style="padding-bottom: 1rem;">
        <div class="catalog_new container-fluid">
            <div class="products container-fluid">
            <!--   <div class="row row-cols-1">
                   <div class="col">
                       <div class="head_row"><a style="font-size: 20px"><b>Новинки</b></a></div>
                   </div>
               </div> -->
                <div class="row_info">
                    <a style="font-size: 22px"><b>Лучшие из лучших</b></a>
                </div>
               <div class="row"> <!-- row-cols-5 -->
                   <div class="col-sm-auto col-md-auto col-lg-auto">
                       <div class="product">
                           <div class="product-img">
                               <a href="#"><img class="p_img" src="img/books/бегущий.jpg" alt=""></a>
                           </div>
                           <p class="product-title">
                               <a href="#" style="text-decoration:none">Бегущий в лабиринте</a>
                               <a style="color: #A4A4A4; font-size: 0.6rem">Дэшнер Джеймс</a>
                           </p>
                           <div class="credit">
                               <a style="font-size: 20px"><b>559p.</b></a>
                               <button class="buy_button">Купить</button>
                           </div>
                       </div>
                   </div>
                   <div class="col-sm-auto col-md-auto col-lg-auto">
                       <div class="product">
                           <div class="product-img">
                               <a href="#"><img class="p_img" src="img/books/мараиморок.jpeg" alt=""></a>
                           </div>
                           <p class="product-title">
                               <a href="#"  style="text-decoration:none">Мара и морок</a>
                               <a style="color: #A4A4A4; font-size: 0.6rem">Арден Ли</a>
                           </p>
                           <div class="credit">
                               <a style="font-size: 20px"><b>699p.</b></a>
                               <button class="buy_button">Купить</button>
                           </div>
                       </div>
                   </div>
                   <div class="col-sm-auto col-md-auto col-lg-auto">
                       <div class="product">
                           <div class="product-img">
                               <a href="#"><img class="p_img" src="img/books/властелин%20колец.jpg" alt=""></a>
                           </div>
                           <p class="product-title">
                               <a href="#"  style="text-decoration:none">Властелин колец</a>
                               <a style="color: #A4A4A4; font-size: 0.6rem">Руэл Толкин</a>
                           </p>
                           <div class="credit">
                               <a style="font-size: 20px"><b>559p.</b></a>
                               <button class="buy_button">Купить</button>
                           </div>
                       </div>
                   </div>
                   <div class="col-sm-auto col-md-auto col-lg-auto">
                       <div class="product">
                           <div class="product-img">
                               <a href="#"><img class="p_img" src="img/books/гарри%20поттер.jpg" alt=""></a>
                           </div>
                           <p class="product-title">
                               <a href="#"  style="text-decoration:none">Гарри Поттер. Книга 1-ая</a>
                               <a style="color: #A4A4A4; font-size: 0.6rem">Роан Джоулинг</a>
                           </p>
                           <div class="credit">
                               <a style="font-size: 20px"><b>729p.</b></a>
                               <button class="buy_button">Купить</button>
                           </div>
                       </div>
                   </div>
                   <div class="col-sm-auto col-md-auto col-lg-auto">
                       <div class="product">
                           <div class="product-img">
                               <a href="#"><img class="p_img" src="img/books/саксонец.jpg" alt=""></a>
                           </div>
                           <p class="product-title">
                               <a href="#"  style="text-decoration:none">Саксонец. Меч Роланда</a>
                               <a style="color: #A4A4A4; font-size: 0.6rem">Тим Севери</a>
                           </p>
                           <div class="credit">
                               <a style="font-size: 20px"><b>499p.</b></a>
                               <button class="buy_button">Купить</button>
                           </div>
                       </div>
                   </div>
                   <div class="col-sm-auto col-md-auto col-lg-auto">
                       <div class="product">
                           <div class="product-img">
                               <a href="#"><img class="p_img" src="img/books/игра%20престолов.jpg" alt=""></a>
                           </div>
                           <p class="product-title">
                               <a href="#"  style="text-decoration:none">Игра престолов</a>
                               <a style="color: #A4A4A4; font-size: 0.6rem">Джордж Р.Р. Мартин</a>
                           </p>
                           <div class="credit">
                               <a style="font-size: 20px"><b>559p.</b></a>
                               <button class="buy_button">Купить</button>
                           </div>
                       </div>
                   </div>

               </div>
           </div>
       </div>
    </div>

    <div class="column_line">
        <div class="catalog_new container-fluid">
            <div class="products container-fluid">
                <!--   <div class="row row-cols-1">
                       <div class="col">
                           <div class="head_row"><a style="font-size: 20px"><b>Новинки</b></a></div>
                       </div>
                   </div> -->
                <div class="row_info">
                    <a style="color: #eeeeee; font-size: 22px"><b>Новинки литературы</b></a>
                </div>
                <div class="row"> <!-- row-cols-5 -->
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_newes">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/бегущий.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none; color: white">Бегущий в лабиринте</a>
                                <a style="color: white; font-size: 0.6rem">Дэшнер Джеймс</a>
                            </p>
                            <div class="credit">
                                <a class="price_newes"><b>559p.</b></a>
                                <button class="buy_button_newes">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_newes">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/мараиморок.jpeg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none; color: white">Мара и морок</a>
                                <a style="color: white; font-size: 0.6rem">Арден Ли</a>
                            </p>
                            <div class="credit">
                                <a class="price_newes"><b>699p.</b></a>
                                <button class="buy_button_newes">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_newes">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/властелин%20колец.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none; color: white">Властелин колец</a>
                                <a style="color: white; font-size: 0.6rem">Руэл Толкин</a>
                            </p>
                            <div class="credit">
                                <a class="price_newes"><b>559p.</b></a>
                                <button class="buy_button_newes">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_newes">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/гарри%20поттер.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none; color: white">Гарри Поттер. Книга 1-ая</a>
                                <a style="color: white; font-size: 0.6rem">Роан Джоулинг</a>
                            </p>
                            <div class="credit">
                                <a class="price_newes"><b>729p.</b></a>
                                <button class="buy_button_newes">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_newes">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/саксонец.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none; color: white">Саксонец. Меч Роланда</a>
                                <a style="color: white; font-size: 0.6rem">Тим Севери</a>
                            </p>
                            <div class="credit">
                                <a class="price_newes"><b>499p.</b></a>
                                <button class="buy_button_newes">Купить</button>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_newes">
                            <div class="product-img">
                                <a href="#"><img class="p_img" src="img/books/игра%20престолов.jpg" alt=""></a>
                            </div>
                            <p class="product-title">
                                <a href="#"  style="text-decoration:none; color: white">Игра престолов</a>
                                <a style="color: white; font-size: 0.6rem">Джордж Р.Р. Мартин</a>
                            </p>
                            <div class="credit">
                                <a class="price_newes"><b>559p.</b></a>
                                <button class="buy_button_newes">Купить</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="column_lines">
        <div class="catalog_new container">
            <div class="products container-fluid">
                <div class="row_info">
                    <a style="font-size: 22px"><b>Книжные циклы</b></a>
                </div>
                <div class="row"> <!-- row-cols-5 -->
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_cycle">
                            <div class="product_cycle-img">
                                <a href="#"><img class="p_c_img" src="img/books/атакатитанов.png" alt=""></a>
                            </div>
                            <p class="product_cycle-title">
                                <a href="#"  style="text-decoration:none; font-size: 1rem">Атака титанов</a>
                                <a style="color: #A4A4A4">Борьба человечества с ужасными титанами</a>
                            </p>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_cycle">
                            <div class="product_cycle-img">
                                <a href="#"><img class="p_c_img" src="img/books/ведьминаслужба.png" alt=""></a>
                            </div>
                            <p class="product_cycle-title">
                                <a href="#"  style="text-decoration:none; font-size: 1rem">Ведьмина служба доставки</a>
                                <a style="color: #A4A4A4">Маленькая ведьмочка учится помогать людям</a>
                            </p>
                        </div>
                    </div>
                    <div class="col-sm-auto col-md-auto col-lg-auto">
                        <div class="product_cycle">
                            <div class="product_cycle-img">
                                <a href="#"><img class="p_c_img" src="img/books/токийскийгуль.png" alt=""></a>
                            </div>
                            <p class="product_cycle-title">
                                <a href="#"  style="text-decoration:none; font-size: 1rem">Токийский гуль</a>
                                <a style="color: #A4A4A4">Фантастическая драма о противостоянии людей и гулей</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?
include("footer.phtml");
?>